version: '3'
services:
  homeassistant:
    user: "${DOCKER_USER}"
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - "${PROJECT_DIRECTORY}/config:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"
    network_mode: host
    privileged: true
    restart: unless-stopped
    user: "${DOCKER_USER}"

